/// <reference lib="webworker" />
// Generated by Serwist - see apps/web/src/app/sw.ts (this file).
// Built output lands at apps/web/public/sw.js.
//
// The InjectManifest pattern (configured in next.config.ts) replaces
// `self.__SW_MANIFEST` with the build-time precache list of static
// assets emitted by `next build`. The Serwist class below is the
// single high-level runtime entry point: it registers install/activate/
// fetch handlers, wires the precache, and applies our runtime cache
// strategies (NetworkFirst for /api/backend/*, CacheFirst for
// /_next/static, offline fallback to /offline).
import { defaultCache } from '@serwist/next/worker';
import {
  NetworkFirst,
  type PrecacheEntry,
  type SerwistGlobalConfig,
  Serwist,
  ExpirationPlugin,
} from 'serwist';

declare global {
  interface WorkerGlobalScope extends SerwistGlobalConfig {
    __SW_MANIFEST: (PrecacheEntry | string)[] | undefined;
  }
}
declare const self: ServiceWorkerGlobalScope;

const serwist = new Serwist({
  precacheEntries: self.__SW_MANIFEST,
  skipWaiting: true,
  clientsClaim: true,
  navigationPreload: true,
  runtimeCaching: [
    // NetworkFirst for /api/backend/* (leads, visits, notifications):
    // try cache, fall back to network, fall back to stale-while-revalidate.
    {
      matcher: ({ url }) => url.pathname.startsWith('/api/backend/'),
      handler: new NetworkFirst({
        cacheName: 'shadhil-api',
        networkTimeoutSeconds: 4,
        plugins: [
          new ExpirationPlugin({
            maxEntries: 200,
            maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
            purgeOnQuotaError: true,
          }),
        ],
      }),
    },
    // Defer everything else to the defaultCache rules (static assets,
    // Google Fonts, Next.js static chunks, image assets). The default
    // cache uses CacheFirst for /_next/static, StaleWhileRevalidate for
    // images and fonts.
    ...defaultCache,
  ],
  fallbacks: {
    entries: [
      {
        matcher: ({ request }) => request.destination === 'document',
        url: '/offline',
      },
    ],
  },
});

serwist.addEventListeners();

// ────────────────────────────────────────────────────────────────────────────
// Web push (T-PUSH, 2026-09-08)
// ────────────────────────────────────────────────────────────────────────────
// Handle incoming push events: parse the JSON payload ({ title, body, url })
// and show a notification. Clicking it focuses/opens the target URL.
self.addEventListener('push', (event) => {
  let title = 'Shadhil CRM';
  let body = '';
  let url = '/';
  try {
    const parsed = event.data ? event.data.json() : {};
    title = parsed.title ?? title;
    body = parsed.body ?? '';
    url = parsed.url ?? url;
  } catch {
    // non-JSON payload - fall back to the raw text
    title = event.data?.text() ?? title;
  }
  const options: NotificationOptions = {
    body,
    icon: '/icons/apple-touch-180.png',
    badge: '/icons/apple-touch-180.png',
    data: { url },
  };
  event.waitUntil(self.registration.showNotification(title, options));
});

// Clicking a notification focuses the app and navigates to the target URL.
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const url = (event.notification.data as { url?: string } | undefined)?.url ?? '/';
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      for (const client of clients) {
        if ('focus' in client) {
          client.focus();
          if ('navigate' in client) {
            void client.navigate(url);
          }
          return;
        }
      }
      return self.clients.openWindow(url);
    }),
  );
});
