/// <reference lib="webworker" />
// Generated by Serwist - see apps/web/src/app/sw.ts (this file).
// Built output lands at apps/web/public/sw.js.
//
// The InjectManifest pattern (configured in next.config.ts) replaces
// `self.__SW_MANIFEST` with the build-time precache list of static
// assets emitted by `next build`. The Serwist class below is the
// single high-level runtime entry point: it registers install/activate/
// fetch handlers, wires the precache, and applies our runtime cache
// strategies (NetworkFirst for /api/backend/*, CacheFirst for
// /_next/static, offline fallback to /offline).
import { defaultCache } from '@serwist/next/worker';
import {
  NetworkFirst,
  type PrecacheEntry,
  type SerwistGlobalConfig,
  Serwist,
  ExpirationPlugin,
} from 'serwist';

declare global {
  interface WorkerGlobalScope extends SerwistGlobalConfig {
    __SW_MANIFEST: (PrecacheEntry | string)[] | undefined;
  }
}
declare const self: ServiceWorkerGlobalScope;

const serwist = new Serwist({
  precacheEntries: self.__SW_MANIFEST,
  skipWaiting: true,
  clientsClaim: true,
  navigationPreload: true,
  runtimeCaching: [
    // NetworkFirst for /api/backend/* (leads, visits, notifications):
    // try cache, fall back to network, fall back to stale-while-revalidate.
    {
      matcher: ({ url }) => url.pathname.startsWith('/api/backend/'),
      handler: new NetworkFirst({
        cacheName: 'shadhil-api',
        networkTimeoutSeconds: 4,
        plugins: [
          new ExpirationPlugin({
            maxEntries: 200,
            maxAgeSeconds: 7 * 24 * 60 * 60, // 7 days
            purgeOnQuotaError: true,
          }),
        ],
      }),
    },
    // Defer everything else to the defaultCache rules (static assets,
    // Google Fonts, Next.js static chunks, image assets). The default
    // cache uses CacheFirst for /_next/static, StaleWhileRevalidate for
    // images and fonts.
    ...defaultCache,
  ],
  fallbacks: {
    entries: [
      {
        matcher: ({ request }) => request.destination === 'document',
        url: '/offline',
      },
    ],
  },
});

serwist.addEventListeners();
