/**
 * Types for the offline-store package.
 *
 * Platform-agnostic: no React, no Next.js, no Expo imports.
 * Both `apps/web` (PWA) and `apps/mobile` (Expo, future) consume these.
 */

/**
 * A pending mutation waiting to be replayed against the server.
 *
 * `body` is JSON-serializable for application/json content; photo uploads
 * reference a blob by `blobKey` (stored in the `photos` IDB store) and
 * use multipart/form-data encoding.
 */
export type Mutation = {
  /** UUID v4, generated by the queue on enqueue. */
  id: string;
  /** Path component, e.g. `/leads` or `/leads/abc/photos`. No host. */
  endpoint: string;
  method: 'POST' | 'PATCH' | 'PUT' | 'DELETE';
  /** JSON body for application/json; undefined for multipart. */
  body?: unknown;
  /** Content-Type for the replay request. */
  contentType?: 'application/json' | 'multipart/form-data';
  /** Extra headers (auth tokens, request IDs). */
  headers?: Record<string, string>;
  /** IDB key in the photos store; required for multipart contentType. */
  blobKey?: string;
  /** Filename for the multipart file part; defaults to 'photo.webp'. */
  blobName?: string;
  /** When this mutation was enqueued (epoch ms). */
  createdAt: number;
  /** How many times replay has retried this mutation. */
  retries: number;
  /** Set on last replay attempt if the server returned >= 400. */
  lastError?: string;
  /**
   * Logical-operation key for dedupe (T-D4). When set, `enqueueUnique`
   * replaces an existing queued entry with the same key instead of
   * appending a duplicate (e.g. `outcome:{visitId}:{outcome}`). Not
   * used by plain `enqueue` — the field is optional so existing
   * enqueued entries and the SW replay path are unaffected.
   */
  dedupeKey?: string;
};

/**
 * Phase emitted by the mutation queue's `subscribe()` callback. Pages
 * can listen to drive UI state (toasts, badges, "X queued" count).
 */
export type OfflineState = {
  phase: 'idle' | 'enqueued' | 'replaying' | 'replayed' | 'pruned';
  item?: Mutation;
  count: number;
};

/**
 * Returned by `replay()`. The caller uses this to update UI
 * (e.g. show "3 synced, 1 failed" toast).
 */
export type ReplayResult = {
  succeeded: number;
  failed: Mutation[];
  retried: number;
};

/**
 * Discriminated union return type for the `withOffline()` wrapper
 * (apps/web/src/lib/with-offline.ts). The form's success handler
 * branches on `kind` to decide UI: "Saved" vs "Saved locally".
 */
export type OfflineMutationResult<TData> =
  | { kind: 'synced'; data: TData; queuedAt?: undefined }
  | { kind: 'queued'; id: string; queuedAt: number; data?: undefined }
  | { kind: 'failed'; error: Error; data?: undefined };
